// Code generated by "stringer -type Tristate"; DO NOT EDIT.

package errcheck

import "strconv"

const _Tristate_name = "UnknownYesNo"

var _Tristate_index = [...]uint8{0, 7, 10, 12}

func (i Tristate) String() string {
	if i >= Tristate(len(_Tristate_index)-1) {
		return "Tristate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tristate_name[_Tristate_index[i]:_Tristate_index[i+1]]
}
